24 implements mailing service
Los-nonos/Gryffindor pull request #37
Opened 2020-04-13 14:11 UTC by JoaquinMartina

- Implements class EmailJob (basado en la documentacion de Laravel y su uso de trabajos con colas)
- Implements class EmailDispatcherService

2020-04-13 23:35 UTC, cristianvena18 requested changes
La implementación del despacho de correos está medianamente bien.
unos puntos que ví:
* falta dejar fácil de cambiar el correo y el nombre del email que envia
* nunca se rellenó el dto de email para generar el despacho de correo o al menos no se dejó claro

mi recomendación es hacer un dto para ambos correos, tanto para el que se envía como el que recibe el email, el que recibe el email con los datos, nombre direccion e información, y el que envía que tenga solamente el nombre y la dirección.
entonces dejas un servicio que se encargue de conseguir el dto de envio y así vos te desligas de esa lógica, y armas en el lugar de despacho un dto con la información y lanzas el evento

2020-04-14 00:23 UTC, MartinMontanari requested changes
Dejé comentarios en los archivos.
Son similares a los comentarios de Cris.
Si bien la solución que yo planteo no es la acertada para atender a la issue completamente, dejaría el camino marcado para poder atender los diferentes CU en el futuro.
Por favor revisar y atender el caso de uso correctamente.
Gracias!

2020-04-14 00:23 UTC, MartinMontanari commented on .env.example
>  MAIL_FROM_NAME="${APP_NAME}"
Keys de producción en el .env.example no.
Compartí esas keys exportando el .env actualizado al grupo de Slack y que cada uno las guarde.

2020-04-14 00:23 UTC, MartinMontanari commented on Application/Jobs/EmailJob.php
> +    }
Falta de abstracción, la implementación deber ser agnóstica.
El objeto y la clase deberían llamarse $emailToSend = new FormDataEmail(bla bla bla);   -> si el día de mañana cambiamos de servicio no necesitaríamos refactorizar ésto.

2020-04-14 00:23 UTC, MartinMontanari commented on Application/Services/Email/emailDispatcherServiceInterface.php
> +    public function handle($emailDetail);
Idem al anterior.

2020-04-14 00:23 UTC, MartinMontanari commented on Application/Services/Email/emailDispatcherService.php
> +        EmailJob::dispatch($emailDetail)->onQueue('emails');
Acá debería agregar el tipo específico del objeto a retornar. Un objeto del tipo Email precisamente.

2020-04-14 00:23 UTC, MartinMontanari commented on Infrastructure/Email/SenGrid/SendGridEmail.php
> +}
Ésto debe ser dinámico, los campos deben tomar los datos enviados desde un formulario. 
En éste caso para probar y dejar el endpoint listo atendiendo un caso de uso real, podrías cambiar el nombre de la clase a un SendContactForm y que retorne un email tomando los datos que pertenecen al formulario de contacto (Los datos que recibirá el endpoint son: [Vista formulario contacto](https://github.com/Los-nonos/ZeepCommerce/issues/95))

2020-04-14 00:23 UTC, MartinMontanari commented on resources/views/email/test.blade.php
> +<h1>Mensaje de correo electronico de prueba</h1>
Aquí el correo de prueba debe enviar los datos que recibiste al formatear el email en el proceso.
De esa forma comprobas que el parseo de los datos es correcto.
Sino nunca vas a saber si los datos llegan bien para ser enviados.

Además debés cambiar el nombre de la vista del formuario, al atender el caso de uso SendContactForm debe ser contactForm.blade.php

2020-04-14 00:33 UTC, MartinMontanari commented on Infrastructure/Email/SenGrid/SendGridEmail.php
> +}
La solución real es aplicar un DTO como dijo el Cris y abstraer todo a un objeto FormatEmail y SendEmail.

2020-04-20 22:16 UTC, cristianvena18 requested changes
muy bien, hay un error en el nombre que dejé en el comentario y también falta toda la lógica de notifiable intraaplicación

2020-04-20 22:16 UTC, cristianvena18 commented on Domain/Interfaces/Services/Notifications/NotificationInterface.php
> +interface NotificationInterface
debería ser NotifiableInterface no NotificationInterface

2020-04-20 23:13 UTC, MartinMontanari approved these changes
Muy bien!! Se entiende todo perfectamente y ya se puede consumir el servicio!!
Excelente laburo!
Muchas gracias!!

Solo resta hacer ese cambio que te remarcó el Cris y reparar el conflicto con el composer.lock, pero el resto está perfecto.
Review finalizado, aprobado!

2020-04-25 14:58 UTC, cristianvena18 approved these changes
muy bien chaco

2020-04-27 21:01 UTC, merged