38 implement notifier service
Los-nonos/Gryffindor pull request #40
Opened 2020-04-24 18:27 UTC by JoaquinMartina

Se logro una mejor implementacion en el Servicio e Interfaces de Notificacion 

Close #38

2020-04-25 15:18 UTC, cristianvena18 requested changes
te dejé un par de comentarios, no está mal como lo encaraste pero hay varias cosas que revisar

2020-04-25 15:18 UTC, cristianvena18 commented on Application/Services/Notification/InternalNotificationServiceInterface.php
> +interface InternalNotificationServiceInterface
yo no sé si haría un servicio distinto, yo lo dejaría en el mismo servicio de notifiable, porque es una sola responsabilidad, notificar, por distintos medios pero es el mismo

2020-04-25 15:18 UTC, cristianvena18 commented on Domain/Interfaces/Services/Notifications/NotifiableInterface.php
> +    public function getUserId(): int;
porque agregas otros métodos?

2020-04-25 15:18 UTC, cristianvena18 commented on Domain/Interfaces/Services/Notifications/NotificationInterface.php
> +interface NotificationInterface
usa la misma interfaz que el otro servicio de notificaciones

2020-04-25 15:18 UTC, cristianvena18 commented on Domain/ValueObjects/Notification.php
> +abstract class Notification implements NotifiableInterface
la idea es tener una sola clase que se pueda usar para ambos dispatchers, en algunos tenés valores no requeridos y en el otro no, pero son la misma clase

2020-04-25 15:18 UTC, cristianvena18 commented on Application/Services/Notification/InternalNotificationService.php
> +class InternalNotificationService implements InternalNotificationServiceInterface
usar el mismo servicio de notificaciones con dos funciones:
`sendEmail(NotifiableInterface $notifiable): void;`
`sendNotification(NotifiableInterface $notifiable): void;`

2020-04-25 15:18 UTC, cristianvena18 commented on Application/Events/InternalNotificationEventData.php
> +        return ['mail', 'database'];
devolver un value object con prioridades no con las funciones concretas. depender de abstracciones nunca de implementaciones

2020-04-25 15:18 UTC, cristianvena18 commented on Application/Events/InternalNotificationEventData.php
> +            //Deberia poder obtener el email del UserId -> se me ato la rama
esto simplemente cuando el servicio de notificaciones reciba y ya haya realizado todas las comprobaciones de prioridad y toda la bola llame a la función del user service para buscar por email, eso le devuelve el usuario y obtiene el id por ahí

2020-04-25 15:18 UTC, cristianvena18 commented on Application/Events/InternalNotificationEventData.php
> +        return ['mail', 'database'];
eso debería ser más o menos:
```suggestion
        return ['high' => 'mail', 'middle' => 'database', 'low' => 'database' ];
```

2020-04-27 19:55 UTC, JoaquinMartina commented on Domain/Interfaces/Services/Notifications/NotifiableInterface.php
> +    public function getUserId(): int;
Estos metodos los agrego para poder setear y obtener los datos ya sea de un email o de una notificacion... esta mal encarado?

2020-04-29 01:40 UTC, cristianvena18 approved these changes
muy bien, bien implementado y bien encarado ahora, felicitaciones chaco, queda eso que no te lo pongo como requested changes pero habría que verlo bien después, sin mayores dudas approved

2020-04-29 01:40 UTC, cristianvena18 commented on Application/Services/Notification/NotifiableService.php
> +                                NotificationInterface $mailable,
porqué agregaste dos inyecciones de lo mismo?

2020-04-29 01:40 UTC, cristianvena18 commented on Domain/Enums/Priority.php
> +final class Priority extends Enum
Si bien no miré mucho que te provee esta clase Enum no creo que te haga falta extenderlo de eso, porque al final son constantes simplemente

2020-04-29 15:28 UTC, merged