46 products crud_WIP
Los-nonos/Gryffindor pull request #49
Opened 2020-06-18 23:14 UTC by MartinMontanari

WIP to issue #46

2020-06-18 23:28 UTC, cristianvena18 requested changes
revisa los comentarios

2020-06-18 23:28 UTC, cristianvena18 commented on app/Exceptions/InvalidBodyException.php
> +class InvalidBodyException extends \Exception
why? eso era para que el error handler me lo encontrara, porque lo cambiaste?

2020-06-18 23:28 UTC, cristianvena18 commented on domain/Entities/Product.php
> +    private array $providersId;
esto va en la otra entidad y los arrays no los pongas como tipo porque te hace renegar

2020-06-18 23:28 UTC, cristianvena18 commented on domain/Entities/Product.php
> +    public function getIva(): float
que tenés con el iva? es un impuesto al final

2020-06-18 23:28 UTC, cristianvena18 commented on domain/Entities/Product.php
> +        $this->categoriesId[] = $categories;
es categories el nombre, si no te patea la bdd

2020-06-18 23:28 UTC, cristianvena18 commented on domain/Entities/Product.php
>      {
no era una entidad el stock?

2020-06-18 23:28 UTC, cristianvena18 commented on domain/Entities/Product.php
> +    public function setNotAvailable(bool $notAvailable) : void
si un nombre de método es setnotavailable no tiene sentido que le permitas pasar argumentos al que lo consume, tiene que setear falso si o si, cambia el nombre o sacale el argumento

2020-06-18 23:28 UTC, cristianvena18 commented on infrastructure/Persistence/Repositories/ProductRepository.php
> +        //TODO WTF? REPOSITORY?? DOOOOCTRINE
que tenés con esto?

2020-06-19 11:14 UTC, MartinMontanari commented on app/Exceptions/InvalidBodyException.php
> +class InvalidBodyException extends \Exception
Porque lo escapé para asegurarme que funcione, luego lo acomodaba. Si está mal ahora lo cambio a como estaba

2020-06-19 11:14 UTC, MartinMontanari commented on domain/Entities/Product.php
> +    private array $providersId;
OKok

2020-06-19 11:15 UTC, MartinMontanari commented on domain/Entities/Product.php
> +    public function getIva(): float
Porque no todos los productos tienen el mismo margen/porcentaje/coeficiente de iva.

2020-06-19 11:15 UTC, MartinMontanari commented on domain/Entities/Product.php
> +        $this->categoriesId[] = $categories;
Ya corrijo :ok_hand:

2020-06-19 11:16 UTC, MartinMontanari commented on domain/Entities/Product.php
>      {
es una entidad que a su vez mantendrá su propia lógica, para probar persistir el producto y que funcione el service con setearle un stock hardcodeado me alcanza. 
Luego cuando se ataque stock se retocará ésto.

2020-06-19 11:17 UTC, MartinMontanari commented on domain/Entities/Product.php
> +    public function setNotAvailable(bool $notAvailable) : void
Ya lo corrijo :ok_hand:

2020-06-19 11:18 UTC, MartinMontanari commented on infrastructure/Persistence/Repositories/ProductRepository.php
> +        //TODO WTF? REPOSITORY?? DOOOOCTRINE
Nada, solo que aún lo tengo que hacer y me dejé el recordatorio. Debería haber ignorado el archivo en el PR, se me chispoteó.

2020-06-19 11:21 UTC, MartinMontanari commented
PR on WIP.

2020-07-21 01:08 UTC, closed without merging